var crewData = [
  {
		"id":"",
		"name": "NFN/NMI Llei'rala",
    "title": "Lt. Cmdr. Dr. Llei'rala  M.D./Ph.D",
    "profileImg": "crew/Lleirala.png",
    "pronouns": "She/They, She/her preferred in professional contexts.",
    "pronounsShort": "She/They",
    "rank": "Lieutenant Commander",
    "serial": "X-612-413",
    "division": "Science",
    "assignment": "Chief Medical Officer",
    "species": "Romulan",
    "dob": "2369",
    "pob": "Dier'Dalan",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Lok",
    "title": "Capt. Lok",
    "profileImg": "crew/Lok.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Captain",
    "serial": "",
    "division": "Command",
    "assignment": "Captain",
    "species": "J'naii",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Ignatious Floofles",
    "title": "Dr. Floofles",
    "profileImg": "crew/Floofles.png",
    "pronouns": "It/They",
    "pronounsShort": "It/They",
    "rank": "Commander",
    "serial": "",
    "division": "Science",
    "assignment": "Councilor",
    "species": "Tribble Colony",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Tobias Knight",
    "title": "Cmdr. Tobias Knight",
    "profileImg": "crew/Knight.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Commander",
    "serial": "",
    "division": "Command",
    "assignment": "Tacitcal Officer",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Ezra Kaleo",
    "title": "Cmdr. Ezra Kaleo",
    "profileImg": "crew/Kaleo.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Commander",
    "serial": "",
    "division": "Command",
    "assignment": "Executive Officer",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Azie Concrex",
    "title": "Lt. Cmdr. Azie Concrex",
    "profileImg": "crew/Concrex.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant Commander",
    "serial": "",
    "division": "Engineering",
    "assignment": "Chief Operations Officer",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "NFN/NMI Katag",
    "title": "Lt. Cmdr. Katag",
    "profileImg": "crew/Katag.png",
    "pronouns": "None, He/They if you must",
    "pronounsShort": "None",
    "rank": "Lieutenant Commander",
    "serial": "",
    "division": "Science",
    "assignment": "Science Department Head",
    "species": "Tholian",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Pavil Shran",
    "title": "Lt. Cmdr. Pavil Shran",
    "profileImg": "crew/Shran.png",
    "pronouns": "They/Them",
    "pronounsShort": "They/Them",
    "rank": "Lieutenant Commander",
    "serial": "",
    "division": "Science",
    "assignment": "Head of Astrometrics",
    "species": "Andorian",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "NFN/NMI Bune",
    "title": "Lt. Bune",
    "profileImg": "crew/Bune.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Engineering",
    "assignment": "Engineering Officer",
    "species": "Ferengi",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Shryreh Kall",
    "title": "Lt. Shryreh Kall",
    "profileImg": "crew/Kall.png",
    "pronouns": "They/Them",
    "pronounsShort": "They/Them",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Command",
    "assignment": "Flight Ops Officer",
    "species": "Andorian",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Tilou Metri",
    "title": "Lt. Tilou Metri",
    "profileImg": "crew/Metri.png",
    "pronouns": "",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant Junior Grade",
    "serial": "",
    "division": "Engineering",
    "assignment": "",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Seshana Rell",
    "title": "Lt. Seshana Rell",
    "profileImg": "crew/Rell.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant",
    "serial": "",
    "division": "",
    "assignment": "",
    "species": "Cardassian",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Drozada Tez",
    "title": "Lt. Drozada Tez",
    "profileImg": "crew/Tez.png",
    "pronouns": "She/They",
    "pronounsShort": "She/They",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Command",
    "assignment": "Security Officer",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "NFN/NMI Zepht",
    "title": "Lt. Zepht",
    "profileImg": "crew/Zepht.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Lieutenant",
    "serial": "ZT-772-289",
    "division": "Command",
    "assignment": "Squadron Leader /\nCrisis Management Specialist",
    "species": "Denobulan",
    "dob": "March 14, 2362, Stardate 40119",
    "pob": "Data Not Available",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Vela Zhal",
    "title": "Lt.Jg. Vela Zhal",
    "profileImg": "crew/Zhal.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant Junior Grade",
    "serial": "84-SY19-117",
    "division": "Operations",
    "assignment": "Security Officer",
    "species": "Orion",
    "dob": "2387",
    "pob": "Orion Frieghter",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "NFN/NMI Velik",
    "title": "CPO Velik",
    "profileImg": "crew/Velik.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Chief Petty Officer",
    "serial": "",
    "division": "Operations",
    "assignment": "Security",
    "species": "Vulcan",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "NFN/NMI T'los",
    "title": "Ensign T'los",
    "profileImg": "crew/Tlos.png",
    "pronouns": "They/Them",
    "pronounsShort": "They/Them",
    "rank": "Ensign",
    "serial": "",
    "division": "Operations",
    "assignment": "",
    "species": "Vulcan",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Zereh Jhahr",
    "title": "Lt. Zereh Jhahr",
    "profileImg": "crew/Jhahr.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Science",
    "assignment": "",
    "": "Aenar",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "NFN/NMI Zirva",
    "title": "Lt. Zirva",
    "profileImg": "crew/Zirva.png",
    "pronouns": "They/Them",
    "pronounsShort": "They/Them",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Operations",
    "assignment": "Peregrin Fighter Pilot, _ Squadron",
    "species": "Trill",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "Starr Deretha Lyalis",
    "title": "Lt. Starr Deretha Lyalis",
    "profileImg": "crew/Lyalis.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Operations",
    "assignment": "Peregrin Fighter Pilot, _ Squadron",
    "species": "Human?",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "NFN/NMI Pid",
    "title": "Lt. Pid",
    "profileImg": "crew/Pid.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Operations",
    "assignment": "Peregrin Fighter Pilot, _ Squadron",
    "species": "Ferengi",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
		"id":"",
		"name": "NFN/NMI Kiisa",
    "title": "Lt. Kiisa",
    "profileImg": "crew/Kiisa.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Science",
    "assignment": "Medical Nurse",
    "species": "Kaitian",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  }/*,

  {
		"id":"",
		"name": "",
    "title": "",
    "profileImg": "crew/",
    "pronouns": "",
    "pronounsShort": "",
    "rank": "",
    "serial": "",
    "division": "",
    "assignment": "",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  }
  */
]