var crewData = [
  {
    "player": "Ada",
    "name": "NFN/NMI Llei'rala",
    "title": "Lt. Cmdr. Dr. Llei'rala  M.D./Ph.D",
    "profileImg": "crew/Lleirala.png",
    "pronouns": "She/They, <br>She/her preferred in professional contexts.",
    "pronounsShort": "She/They",
    "rank": "Lieutenant Commander",
    "serial": "X-612-413",
    "division": "Science",
    "assignment": "Chief Medical Officer",
    "species": "Romulan",
    "dob": "2369",
    "pob": "Dier'Dalan",
    "priorHistory": "<h4>Early Life</h4>Llei'rala grew up with her parents, Kenra'sere and Seihwi, on the small Romulan Empire colony of Dier'Dalan. By all accounts she showed an early talent and enthusiasm for medicine. In 2374 the colony was attacked by the dominion. Llei'rala and her mother Kenra'sere escaped and began living on Romulus, but her parent Seiwhi died in the attack.  She completed her initial studies on Romulus at the Medical Academy of the Romulan Empire, and began post-graduate studies at the same until 2387. <br>Llei'rala was evacuated from Romulus before it's destruction from the romulan Supernova in 2387. Her mother died in the event. She spent two years volunteering as a medic to help her fellow refugees, before applying to starfleet with a goal of finishing her MD.</p><p><h4>Starfleet Medical Academy</h4>Llei'rala attended Starfleet Medical Academy in 2390 and earned her Doctorate of Medicine and Philosophy in 2395. However, at the time she was only interested in the medical program, and so was not a starfleet cadet; a rare but not unheard of situation.<br>Llei'rala was a rigorous student, and impressed professors with the knowledge she had already gained through prior study. This did not offer much of a shortcut in her studies, however, as her previous time at the Medical Academy of the Romulan Empire did not include nearly as much Xenobiology as required by Starfleet, and a large amount of her existing studies were not accepted.<h4>Starfleet service and Enlistment</h4>Llei'Rala's residency included a tour as a civilian consultant on a starfleet medical ship, cementing her association with the Federation. At the end of that tour, Llei'rala enrolled in Starfleet Academy as a cadet. She was considered a model student and graduated with honors.</p>",
    "serviceRecord": "<ul><li>2395 - Awarded MD-PhD dual degree.      <li>2395 - Residency at Johns Hopkins Hospital (2 years)<li>2397 - Residency as Corpsman on <i>USS Daishan Dao</i> Hospial Ship (2 years)<li>2399 - Enrolled in Starfleet Academy<li>2402 - Graduated with honors from Starfleet Academy and Commissioned as Lieutenant Junior Grade<li>2402 - Assigned to <i>U.S.S. Phan Xi Păng</i> as Medical Officer (2 years)<ul><li>2403 - Captain's Commendation</ul>     <li>2404 - Assigned to <i>U.S.S. Whitney</i> as Medical Officer (5 years)     	<ul><li>2406 - Captain's Commendation<li>2406 - Promoted to Lieutenant<li>2408 - Awarded Starfleet Silver Palm for actions on stardate 57231<li>2409 - Awarded Extended Tour Ribbon </li>         <li>2409 - Promoted to Lieutenant commander</ul></li><li>2409 - Assigned to Starbase 413 as Research Medical Officer<ul><li>2413 - Received The Machri-Cherk award for outstanding medical research<li>2414 - Awarded 20 Years of Service Ribbon</ul><li>2416 - Assigned to <i>U.S.S. Sierra</i> as Chief Medical Officer</ul>"
  },
  {
    "player": "NPC",
    "name": "Lok",
    "title": "Capt. Lok",
    "profileImg": "crew/Lok.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Captain",
    "serial": "",
    "division": "Command",
    "assignment": "Captain",
    "species": "J'naii",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "Tracy",
    "name": "Ignatious Floofles",
    "title": "Dr. Floofles",
    "profileImg": "crew/Floofles.png",
    "pronouns": "It/They",
    "pronounsShort": "It/They",
    "rank": "Commander",
    "serial": "",
    "division": "Science",
    "assignment": "Councilor",
    "species": "Tribble Colony",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "Tobias Knight",
    "title": "Cmdr. Tobias Knight",
    "profileImg": "crew/Knight.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Commander",
    "serial": "",
    "division": "Command",
    "assignment": "Tacitcal Officer",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "Ezra Kaleo",
    "title": "Cmdr. Ezra Kaleo",
    "profileImg": "crew/Kaleo.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Commander",
    "serial": "",
    "division": "Command",
    "assignment": "Executive Officer",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "Azie Concrex",
    "title": "Lt. Cmdr. Azie Concrex",
    "profileImg": "crew/Concrex.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant Commander",
    "serial": "",
    "division": "Engineering",
    "assignment": "Chief Operations Officer",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "Mekk",
    "name": "NFN/NMI Katag",
    "title": "Lt. Cmdr. Katag",
    "profileImg": "crew/Katag.png",
    "pronouns": "None, He/They if you must",
    "pronounsShort": "None",
    "rank": "Lieutenant Commander",
    "serial": "",
    "division": "Science",
    "assignment": "Science Department Head",
    "species": "Tholian",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "Tracy",
    "name": "Pavil Shran",
    "title": "Lt. Cmdr. Pavil Shran",
    "profileImg": "crew/Shran.png",
    "pronouns": "They/Them",
    "pronounsShort": "They/Them",
    "rank": "Lieutenant Commander",
    "serial": "",
    "division": "Science",
    "assignment": "Head of Astrometrics",
    "species": "Andorian",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "NFN/NMI Bune",
    "title": "Lt. Bune",
    "profileImg": "crew/Bune.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Engineering",
    "assignment": "Engineering Officer",
    "species": "Ferengi",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "Shryreh Kall",
    "title": "Lt. Shryreh Kall",
    "profileImg": "crew/Kall.png",
    "pronouns": "They/Them",
    "pronounsShort": "They/Them",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Command",
    "assignment": "Flight Ops Officer",
    "species": "Andorian",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "Brett",
    "name": "Tilou Metri",
    "title": "Lt. Tilou Metri",
    "profileImg": "crew/Metri.png",
    "pronouns": "",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant Junior Grade",
    "serial": "",
    "division": "Engineering",
    "assignment": "",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "Mekk",
    "name": "Seshana Rell",
    "title": "Lt. Seshana Rell",
    "profileImg": "crew/Rell.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant",
    "serial": "",
    "division": "",
    "assignment": "",
    "species": "Cardassian",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "Drozada Tez",
    "title": "Lt. Drozada Tez",
    "profileImg": "crew/Tez.png",
    "pronouns": "She/They",
    "pronounsShort": "She/They",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Command",
    "assignment": "Security Officer",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "Scott",
    "name": "NFN/NMI Zepht",
    "title": "Lt. Zepht",
    "profileImg": "crew/Zepht.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Lieutenant",
    "serial": "ZT-772-289",
    "division": "Command",
    "assignment": "Squadron Leader /<br>Crisis Management Specialist",
    "species": "Denobulan",
    "dob": "March 14, 2362, Stardate 40119",
    "pob": "Data Not Available",
    "priorHistory": "<h4>Early Life</h4>Zepht was raised on a Denobulan frontier colony to a pair of diplomats who works to coordinate efforts between the various colony settlements and trade with offworld organizations. From a young age Zepht showed a high aptitude for cooperative task, as well as an interest in shuttles and other small flight craft. His early adult life saw him piloting shuttlecraft carrying supplies, dignitaries, and personnel between the various settlements of the colony, and visiting starships.</p><p><h4>Starfleet Academy</h4>Having lived through the Dominion War during early childhood, Zepht felt the need to do their part when war broke out between the Federation and the Klingon Empire. Enlisting in Starfleet in 2408, they attended a flight and repair school located at the Utopia Planetia shipyards, where several professors noted Zepht's adaptive flight skills and ability direct group tasks to completion far ahead of schedule.  They graduated in 2410 and began their service as a pilot and remote repair technician.</p>",
    "serviceRecord": "<ul> <li>2410 - Completed Enlistment Training, designated as a pilot and repair technician. <li>2410 - Assigned to the USS Thunderchild <ul> <li>2415 - Awarded the Decoration for Valor and Gallantry in 2414 for emergency repairs performs during battle. <li>2415 - Commissioned as an officer, Lieutenant Junior Grade and assigned as a fighter squadron commander. <li>2415 - Awarded Silver Palms for action perform during the Iconian War. <li>2415 - Awarded Extended Tour Ribbon <li>2415 - Granted an Extended Leave of Absence. </ul></li> <li>2415 - Received supplementary emergency response training. <li>2415 - Promoted to Lieutenant Senior Grade <li>2416 - Assigned to U.S.S. Sierra as a squadron commander and emergency response specialist. </li> </ul>"
  },
  {
    "player": "Ada",
    "name": "Vela Zhal",
    "title": "Lt.Jg. Vela Zhal",
    "profileImg": "crew/Zhal.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant Junior Grade",
    "serial": "84-SY19-117",
    "division": "Operations",
    "assignment": "Security Officer",
    "species": "Orion",
    "dob": "2387",
    "pob": "Orion Frieghter",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "Brett",
    "name": "NFN/NMI Velik",
    "title": "CPO Velik",
    "profileImg": "crew/Velik.png",
    "pronouns": "He/Him",
    "pronounsShort": "He/Him",
    "rank": "Chief Petty Officer",
    "serial": "",
    "division": "Operations",
    "assignment": "Security",
    "species": "Vulcan",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "NFN/NMI T'los",
    "title": "Ensign T'los",
    "profileImg": "crew/Tlos.png",
    "pronouns": "They/Them",
    "pronounsShort": "They/Them",
    "rank": "Ensign",
    "serial": "",
    "division": "Operations",
    "assignment": "",
    "species": "Vulcan",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "Zereh Jhahr",
    "title": "Lt. Zereh Jhahr",
    "profileImg": "crew/Jhahr.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Science",
    "assignment": "",
    "species": "Aenar",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "NFN/NMI Zirva",
    "title": "Lt. Zirva",
    "profileImg": "crew/Zirva.png",
    "pronouns": "They/Them",
    "pronounsShort": "They/Them",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Operations",
    "assignment": "Peregrin Fighter Pilot /<br>_ Squadron",
    "species": "Trill",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "Starr Deretha Lyalis",
    "title": "Lt. Starr Deretha Lyalis",
    "profileImg": "crew/Lyalis.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Operations",
    "assignment": "Peregrin Fighter Pilot /<br>_ Squadron",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "NFN/NMI Pid",
    "title": "Lt. Pid",
    "profileImg": "crew/Pid.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Operations",
    "assignment": "Peregrin Fighter Pilot /<br>_ Squadron",
    "species": "Ferengi",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  },
  {
    "player": "NPC",
    "name": "NFN/NMI Kiisa",
    "title": "Lt. Kiisa",
    "profileImg": "crew/Kiisa.png",
    "pronouns": "She/Her",
    "pronounsShort": "She/Her",
    "rank": "Lieutenant",
    "serial": "",
    "division": "Science",
    "assignment": "Medical Nurse",
    "species": "Kaitian",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  }/*,

  {
    "player": "",
    "name": "",
    "title": "",
    "profileImg": "crew/",
    "pronouns": "",
    "pronounsShort": "",
    "rank": "",
    "serial": "",
    "division": "",
    "assignment": "",
    "species": "",
    "dob": "",
    "pob": "",
    "priorHistory": "",
    "serviceRecord": ""
  }
  */
]